enum ActionTypesEnum  {
  ADD_LIST = 'ADD_LIST',
  DELETE_LIST = 'DELETE_LIST',
  EDIT_LIST_TITLE = 'EDIT_DELETE_LIST',
  ADD_CARD = 'ADD_CARD',
  EDIT_CARD = 'EDIT_CARD',
  DELETE_CARD = 'DELETE_CARD',
  ADD_BOARD = 'ADD_BOARD',
  SET_ACTIVE_BOARD = 'SET-ACTIVE_BOARD',
  DRAG_HAPPENED = 'DRAG_HAPPENED'
}

export default ActionTypesEnum
